services:
  app:
    build: .
    user: "${UID}:${GID}"
    ports:
      - "8000:80"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shoptet_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
